language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests --verbosity=2 --with-coverage -x --with-xunit -cover-erase --cover-package=ece
notifications:
  email: false
  slack: w4k2:hi4RvyZzus4WXE7Ea5XufyBU